language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jmpoff/docker-react -f Dockerfile.dev .


# before
#script:
#  - docker run USERNAME/docker-react npm run test -- --coverage
# after
script:
  - docker run -e CI=true jmpoff/docker-react npm run test 

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-react"
#  env: "Dockerreact-env"
#  bucket_name: "elasticbeanstalk-us-west-2-753348154820"
#  bucket_path: "docker-react"
#  on:
#    branch: master
