language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jmpoff/docker-react -f Dockerfile.dev .


# before
#script:
#  - docker run USERNAME/docker-react npm run test -- --coverage
# after
script:
  - docker run -e CI=true jmpoff/docker-react npm run test
